a = input("What do you want the new fasta file to be written to?")
ohoh = open(a,"w")
ohohoh = open("cut_genes.fa")
oh = ohohoh.readlines()

import re
num = []
for i in oh:
    if not i.startswith(">"):
        co = re.findall(r"GAATTC", i)
        num.append(len(co) + 1)

count = 0
for m in oh:
    if m.startswith(">"):
        ohoh.write(m[:10] + "     " + "%d fragments could be generated by cutting this sequence with EcoRI"%(num[count]) + "\n")
        count = count + 1
    else:
        ohoh.write(m)

